Repository UMC-WithMe/WithMe_Back, pull requests merged in 2023-01, with the labels that each got.

#12 ERD, JPA 연관관계를 반영한 Class Diagram 작성
  document/with-me-erd.png
  document/with-me-jpa-cd.drawio.svg
Labels: 📝 documentation

#14 1, 2주차 필요한 Domain 설계 및 구현
  .gitignore
  src/main/java/com/umc/withme/WithMeApplication.java
  src/main/java/com/umc/withme/domain/Address.java
  src/main/java/com/umc/withme/domain/Meet.java
  src/main/java/com/umc/withme/domain/MeetMember.java
  src/main/java/com/umc/withme/domain/Member.java
  src/main/java/com/umc/withme/domain/TotalPoint.java
  src/main/java/com/umc/withme/domain/common/BaseEntity.java
  src/main/java/com/umc/withme/domain/common/BaseTimeEntity.java
  src/main/java/com/umc/withme/domain/constant/Gender.java
  src/main/java/com/umc/withme/domain/constant/MeetCategory.java
  src/main/java/com/umc/withme/domain/constant/MeetStatus.java
  src/main/java/com/umc/withme/domain/constant/RecruitStatus.java
  src/main/java/com/umc/withme/repository/AddressRepository.java
  src/main/resources/junit-platform.properties
  src/test/java/com/umc/withme/repository/AddressRepositoryTest.java
Labels: 💫 feature

#16 작업 중 PR 꼬인 부분들 복구
  .gitignore
  build.gradle
  src/main/java/com/umc/withme/WithMeApplication.java
  src/main/java/com/umc/withme/domain/Address.java
  src/main/java/com/umc/withme/domain/Meet.java
  src/main/java/com/umc/withme/domain/MeetMember.java
  src/main/java/com/umc/withme/domain/Member.java
  src/main/java/com/umc/withme/domain/TotalPoint.java
  src/main/java/com/umc/withme/domain/common/BaseEntity.java
  src/main/java/com/umc/withme/domain/common/BaseTimeEntity.java
  src/main/java/com/umc/withme/domain/constant/Gender.java
  src/main/java/com/umc/withme/domain/constant/MeetCategory.java
  src/main/java/com/umc/withme/domain/constant/MeetStatus.java
  src/main/java/com/umc/withme/domain/constant/RecruitStatus.java
  src/main/java/com/umc/withme/repository/AddressRepository.java
  src/main/resources/application.yaml
  src/main/resources/application.yml
  src/main/resources/junit-platform.properties
  src/test/java/com/umc/withme/WithMeApplicationTests.java
  src/test/java/com/umc/withme/repository/AddressRepositoryTest.java
Labels: 🐛 bug, 💫 feature

#27 API 응답 데이터 정의
  src/main/java/com/umc/withme/dto/common/BaseResponse.java
  src/main/java/com/umc/withme/dto/common/DataResponse.java
  src/main/java/com/umc/withme/dto/common/ErrorResponse.java
  src/main/java/com/umc/withme/exception/ErrorResponse.java
  src/main/java/com/umc/withme/exception/GlobalExceptionHandler.java
Labels: 💫 feature

#20 Exception 처리 환경 구축
  src/main/java/com/umc/withme/domain/Address.java
  src/main/java/com/umc/withme/dto/common/BaseResponse.java
  src/main/java/com/umc/withme/dto/common/DataResponse.java
  src/main/java/com/umc/withme/dto/common/ErrorResponse.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/GlobalExceptionHandler.java
  src/main/java/com/umc/withme/exception/address/AddressNotFoundException.java
  src/main/java/com/umc/withme/exception/common/BadRequestException.java
  src/main/java/com/umc/withme/exception/common/CustomException.java
  src/main/java/com/umc/withme/exception/common/NotFoundException.java
  src/test/java/com/umc/withme/repository/AddressRepositoryTest.java
  src/test/resources/junit-platform.properties
Labels: 💫 feature

#28 Swagger 의존성 추가 및 설정
  build.gradle
  src/main/java/com/umc/withme/config/SwaggerConfig.java
  src/main/resources/application.yaml
Labels: 💫 feature, ⚙️ chore

#30 닉네임 중복 조회 기능 구현
  src/main/java/com/umc/withme/controller/MemberController.java
  src/main/java/com/umc/withme/dto/member/NicknameDuplicationCheckResponse.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/repository/MemeberRepository.java
  src/main/java/com/umc/withme/service/MemberService.java
Labels: 💫 feature

#32 Exception handler에서 Validation 관련 exception인 `ConstraintViolationException`을 처리하지 못하는 문제 해결
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/GlobalExceptionHandler.java
  src/main/java/com/umc/withme/exception/common/CustomException.java
Labels: 🐛 bug

#34 특정 닉네임을 가지는 사용자 프로필 조회
  src/main/java/com/umc/withme/controller/MemberController.java
  src/main/java/com/umc/withme/dto/member/MemberDto.java
  src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/member/NicknameNotFoundException.java
  src/main/java/com/umc/withme/repository/MemberRepository.java
  src/main/java/com/umc/withme/repository/MemeberRepository.java
  src/main/java/com/umc/withme/service/MemberService.java
Labels: 💫 feature

#43 모임 생성 기능 구현
  src/main/java/com/umc/withme/controller/MeetController.java
  src/main/java/com/umc/withme/domain/Meet.java
  src/main/java/com/umc/withme/domain/MeetAddress.java
  src/main/java/com/umc/withme/dto/address/AddressDto.java
  src/main/java/com/umc/withme/dto/address/AddressRequest.java
  src/main/java/com/umc/withme/dto/meet/MeetCreateRequest.java
  src/main/java/com/umc/withme/dto/meet/MeetCreateResponse.java
  src/main/java/com/umc/withme/dto/meet/MeetDto.java
  src/main/java/com/umc/withme/repository/MeetAddressRepository.java
  src/main/java/com/umc/withme/repository/MeetMemberRepository.java
  src/main/java/com/umc/withme/repository/MeetRepository.java
  src/main/java/com/umc/withme/repository/MemberRepository.java
  src/main/java/com/umc/withme/service/MeetService.java
  src/test/java/com/umc/withme/service/MeetServiceTest.java
Labels: 💫 feature

#44 Review와 Point 엔티티 생성
  src/main/java/com/umc/withme/domain/Point.java
  src/main/java/com/umc/withme/domain/Review.java
Labels: 💫 feature

#48 Logging 환경 구축
  build.gradle
  src/main/java/com/umc/withme/config/log/LogTrace.java
  src/main/java/com/umc/withme/config/log/LogTraceAspect.java
  src/main/java/com/umc/withme/config/log/Pointcuts.java
  src/main/java/com/umc/withme/config/log/TraceId.java
  src/main/java/com/umc/withme/config/log/TraceStatus.java
Labels: 💫 feature, ⚙️ chore

#56 회원가입 추가 로직 구현 (폰 번호, 지역 설정)
  src/main/java/com/umc/withme/controller/MemberController.java
  src/main/java/com/umc/withme/domain/Member.java
  src/main/java/com/umc/withme/dto/common/BaseResponse.java
  src/main/java/com/umc/withme/dto/common/DataResponse.java
  src/main/java/com/umc/withme/dto/common/ErrorResponse.java
  src/main/java/com/umc/withme/dto/member/MemberAddressUpdateRequest.java
  src/main/java/com/umc/withme/dto/member/MemberPhoneNumberUpdateRequest.java
  src/main/java/com/umc/withme/service/MemberService.java
  src/test/java/com/umc/withme/service/MemberServiceTest.java
Labels: 💫 feature

#46 인증 기능 구현
  build.gradle
  document/with-me-erd.png
  src/main/java/com/umc/withme/WithMeApplication.java
  src/main/java/com/umc/withme/config/JpaConfig.java
  src/main/java/com/umc/withme/config/SecurityConfig.java
  src/main/java/com/umc/withme/config/SwaggerConfig.java
  src/main/java/com/umc/withme/controller/AuthController.java
  src/main/java/com/umc/withme/controller/HttpRequestController.java
  src/main/java/com/umc/withme/controller/KakaoOAuthController.java
  src/main/java/com/umc/withme/controller/MemberController.java
  src/main/java/com/umc/withme/domain/Member.java
  src/main/java/com/umc/withme/domain/common/BaseEntity.java
  src/main/java/com/umc/withme/domain/constant/Gender.java
  src/main/java/com/umc/withme/domain/constant/RoleType.java
  src/main/java/com/umc/withme/dto/address/AddressDto.java
  src/main/java/com/umc/withme/dto/auth/KakaoOAuthResponse.java
  src/main/java/com/umc/withme/dto/auth/LoginRequest.java
  src/main/java/com/umc/withme/dto/auth/LoginResponse.java
  src/main/java/com/umc/withme/dto/common/BaseResponse.java
  src/main/java/com/umc/withme/dto/common/DataResponse.java
  src/main/java/com/umc/withme/dto/common/ErrorResponse.java
  src/main/java/com/umc/withme/dto/member/MemberAddressUpdateRequest.java
  src/main/java/com/umc/withme/dto/member/MemberDto.java
  src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
  src/main/java/com/umc/withme/dto/member/MemberPhoneNumberUpdateRequest.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/GlobalExceptionHandler.java
  src/main/java/com/umc/withme/exception/auth/KakaoOAuthUnauthorizedException.java
  src/main/java/com/umc/withme/exception/common/UnauthorizedException.java
  src/main/java/com/umc/withme/exception/member/EmailNotFoundException.java
  src/main/java/com/umc/withme/repository/MemberRepository.java
  src/main/java/com/umc/withme/security/JwtAuthenticationFilter.java
  src/main/java/com/umc/withme/security/JwtTokenProvider.java
  src/main/java/com/umc/withme/security/UserDetailsServiceImpl.java
  src/main/java/com/umc/withme/security/WithMeAppPrinciple.java
  src/main/java/com/umc/withme/service/AuthService.java
  src/main/java/com/umc/withme/service/MemberService.java
  src/main/resources/application.yaml
  src/test/java/com/umc/withme/dto/auth/KakaoOAuthResponseTest.java
  src/test/java/com/umc/withme/repository/AddressRepositoryTest.java
  src/test/java/com/umc/withme/service/AuthServiceTest.java
  src/test/java/com/umc/withme/service/MemberServiceTest.java
Labels: 💫 feature, ✅ test, ⚙️ chore

#52 모임 단건 조회 API 생성
  document/with-me-erd.png
  src/main/java/com/umc/withme/controller/MeetController.java
  src/main/java/com/umc/withme/domain/Meet.java
  src/main/java/com/umc/withme/dto/meet/MeetDto.java
  src/main/java/com/umc/withme/dto/meet/MeetInfoGetResponse.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/meet/MeetIdNotFoundException.java
  src/main/java/com/umc/withme/repository/MeetAddressRepository.java
  src/main/java/com/umc/withme/service/MeetService.java
  src/test/java/com/umc/withme/service/MeetServiceTest.java
Labels: 💫 feature

#61 회원 API 수정
  src/main/java/com/umc/withme/controller/MemberController.java
  src/main/java/com/umc/withme/dto/address/AddressDto.java
  src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
  src/main/java/com/umc/withme/dto/member/NicknameDuplicationCheckResponse.java
Labels: 💫 feature, ♻️ refactor

#63 모임 단건 조회 기능 구현
  document/with-me-erd.png
  src/main/java/com/umc/withme/controller/MeetController.java
  src/main/java/com/umc/withme/domain/Meet.java
  src/main/java/com/umc/withme/dto/address/AddressDto.java
  src/main/java/com/umc/withme/dto/address/AddressRequest.java
  src/main/java/com/umc/withme/dto/meet/MeetCreateRequest.java
  src/main/java/com/umc/withme/dto/meet/MeetCreateResponse.java
  src/main/java/com/umc/withme/dto/meet/MeetDto.java
  src/main/java/com/umc/withme/dto/meet/MeetInfoGetResponse.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/meet/MeetIdNotFoundException.java
  src/main/java/com/umc/withme/repository/MeetAddressRepository.java
  src/main/java/com/umc/withme/service/MeetService.java
  src/test/java/com/umc/withme/service/MeetServiceTest.java
Labels: 💫 feature

#53 모임 삭제 API 구현
  src/main/java/com/umc/withme/controller/MeetController.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/common/ForbiddenException.java
  src/main/java/com/umc/withme/exception/meet/MeetDeleteForbiddenException.java
  src/main/java/com/umc/withme/exception/member/MemberIdNotFoundException.java
  src/main/java/com/umc/withme/repository/MeetMemberRepository.java
  src/main/java/com/umc/withme/service/MeetService.java
Labels: 💫 feature

#66 회원 닉네임 설정 API
  src/main/java/com/umc/withme/controller/MemberController.java
  src/main/java/com/umc/withme/domain/Member.java
  src/main/java/com/umc/withme/dto/member/MemberNicknameUpdateRequest.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/common/ConflictException.java
  src/main/java/com/umc/withme/exception/member/NicknameDuplicateException.java
  src/main/java/com/umc/withme/service/MemberService.java
  src/test/java/com/umc/withme/service/MemberServiceTest.java
Labels: 💫 feature

#69 AWS - 서버 배포
  src/main/java/com/umc/withme/controller/AuthController.java
  src/main/resources/application.yaml
  src/test/java/com/umc/withme/repository/AddressRepositoryTest.java
Labels: 🗃 infra

#67 모임 수정 기능 구현
  src/main/java/com/umc/withme/controller/MeetController.java
  src/main/java/com/umc/withme/domain/Meet.java
  src/main/java/com/umc/withme/dto/meet/MeetFormRequest.java
  src/main/java/com/umc/withme/exception/ExceptionType.java
  src/main/java/com/umc/withme/exception/meet/MeetUpdateForbiddenException.java
  src/main/java/com/umc/withme/service/MeetService.java
Labels: 💫 feature, ♻️ refactor
